import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.3.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2024-10",
        enabledModels: [
          "shopifyArticle",
          "shopifyAsset",
          "shopifyBlog",
          "shopifyBulkOperation",
          "shopifyCarrierService",
          "shopifyCollect",
          "shopifyCollection",
          "shopifyComment",
          "shopifyCountry",
          "shopifyCustomer",
          "shopifyCustomerAddress",
          "shopifyDiscount",
          "shopifyDiscountCode",
          "shopifyDraftOrder",
          "shopifyDraftOrderLineItem",
          "shopifyDraftOrderPlatformDiscount",
          "shopifyDraftOrderPlatformDiscountAllocation",
          "shopifyFile",
          "shopifyFulfillment",
          "shopifyFulfillmentEvent",
          "shopifyFulfillmentLineItem",
          "shopifyFulfillmentOrder",
          "shopifyFulfillmentOrderLineItem",
          "shopifyFulfillmentService",
          "shopifyInventoryItem",
          "shopifyInventoryLevel",
          "shopifyLocation",
          "shopifyOrder",
          "shopifyOrderLineItem",
          "shopifyOrderTransaction",
          "shopifyPage",
          "shopifyPriceRule",
          "shopifyProduct",
          "shopifyProductImage",
          "shopifyProductMedia",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifyProductVariantMedia",
          "shopifyProvince",
          "shopifyRefund",
          "shopifyRefundLineItem",
          "shopifyScriptTag",
          "shopifyShippingLine",
          "shopifyTheme",
        ],
        type: "partner",
        scopes: [
          "read_orders",
          "write_customers",
          "read_customers",
          "write_orders",
          "write_order_edits",
          "write_third_party_fulfillment_orders",
          "read_third_party_fulfillment_orders",
          "read_themes",
          "write_themes",
          "read_shipping",
          "read_fulfillments",
          "read_products",
          "write_products",
          "read_content",
          "write_content",
          "read_customer_events",
          "read_delivery_customizations",
          "write_delivery_customizations",
          "read_discounts",
          "write_discounts",
          "read_price_rules",
          "write_fulfillments",
          "read_files",
          "write_files",
          "read_inventory",
          "write_inventory",
          "read_locations",
          "read_merchant_managed_fulfillment_orders",
          "write_merchant_managed_fulfillment_orders",
          "read_metaobject_definitions",
          "write_metaobject_definitions",
          "read_metaobjects",
          "write_metaobjects",
          "read_product_listings",
          "read_publications",
          "write_publications",
          "read_purchase_options",
          "write_purchase_options",
          "read_reports",
          "write_reports",
          "read_returns",
          "write_returns",
          "read_script_tags",
          "write_script_tags",
          "write_shipping",
          "write_pixels",
          "write_assigned_fulfillment_orders",
          "read_assigned_fulfillment_orders",
          "read_online_store_navigation",
          "read_order_edits",
          "write_draft_orders",
          "read_draft_orders",
          "read_payment_terms",
        ],
        customerAuthenticationEnabled: false,
      },
    },
    authentications: {
      settings: {
        redirectOnSignIn: "/sign-in",
        signInPath: "/sign-in",
        unauthorizedUserRedirect: "signInPath",
        defaultSignedInRoles: ["signed-in"],
      },
      methods: {
        googleOAuth: {
          scopes: ["email", "profile"],
          offlineAccess: false,
        },
      },
    },
  },
};
