import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "erpCustomer" model, go to https://kaghati-shopify-v4.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "GnZud7N1RtQo",
  fields: {
    aadharNumber: { type: "string", storageKey: "F1sFBsVcD2dZ" },
    address1: { type: "string", storageKey: "cw6nYE71_2Yd" },
    address2: { type: "string", storageKey: "ilR1J0-xC-Tp" },
    address3: { type: "string", storageKey: "PgwxNJ1238bs" },
    allowBilling: { type: "number", storageKey: "BBfO13UYaouJ" },
    allowLoyalty: { type: "number", storageKey: "MfHAgQI2CZHv" },
    area: { type: "string", storageKey: "mkj_gasSgnHJ" },
    birthdate: { type: "string", storageKey: "6zdU39mFBcNE" },
    city: { type: "string", storageKey: "8_-5S0Wm7FZd" },
    country: { type: "string", storageKey: "2lKBT11SaeDN" },
    creditDays: { type: "number", storageKey: "CoGQJKu97ovO" },
    creditDaysLeft: { type: "number", storageKey: "xa-uV-Gb4lqB" },
    creditLimit: { type: "number", storageKey: "d60EGAtw7e0v" },
    customerAlias: { type: "string", storageKey: "MLVqFAnduQH9" },
    customerId: { type: "string", storageKey: "jtN9v2FFBwiC" },
    customerTypeCode: { type: "number", storageKey: "2jelyy8_7Kw3" },
    email: { type: "string", storageKey: "HczxavEAnG-2" },
    erpId: { type: "number", storageKey: "BCbhHzlI0igi" },
    gstNumber: { type: "string", storageKey: "72cIdf5xcRDK" },
    gstRegType: { type: "number", storageKey: "sptB3Luuf17P" },
    isCreditAllowed: { type: "number", storageKey: "RCtwNnK-hGxV" },
    isFree: { type: "number", storageKey: "2qNz2ktPJkne" },
    isGstExempted: { type: "boolean", storageKey: "_-OXzfGSvj0W" },
    isOffer: { type: "number", storageKey: "e44DlIoL3E1V" },
    isQty: { type: "number", storageKey: "jnLJGllfQDv6" },
    latitude: { type: "string", storageKey: "ae-W2Btxyp8e" },
    loginId: { type: "string", storageKey: "-DiD5Wizaw4r" },
    longitude: { type: "string", storageKey: "NomGASCQiMuj" },
    loyaltyValue: { type: "number", storageKey: "C4KM0JtkPLcI" },
    marriageDate: { type: "string", storageKey: "8fyp087ULcZr" },
    mobile: { type: "string", storageKey: "eRPPf37X5Z9Z" },
    name: { type: "string", storageKey: "giAKyCFvXuM_" },
    outstanding: { type: "number", storageKey: "HPWmSOs_0q9p" },
    panNumber: { type: "string", storageKey: "pgpAhbRYaTrA" },
    phone1: { type: "string", storageKey: "f4O2mpN9V7gx" },
    phone2: { type: "string", storageKey: "RvDLgPXtqKHW" },
    phone3: { type: "string", storageKey: "oIWSTWufsd8j" },
    pincode: { type: "string", storageKey: "g48hiVZSJGoT" },
    priceLevelId: { type: "number", storageKey: "a8I-qGFtdpWq" },
    retailOutletId: { type: "number", storageKey: "b4T1sXDXF9lf" },
    salesMan: { type: "string", storageKey: "Lm0EP31pVPhd" },
    salesManCode: { type: "number", storageKey: "WpIWWhIArnUw" },
    salesManMobile: { type: "string", storageKey: "ELLV121HUy-G" },
    state: { type: "string", storageKey: "ejqBAIUiSty6" },
    stateCode: { type: "number", storageKey: "9flY2hftC7tE" },
    status: { type: "string", storageKey: "3O0OnWXWrROG" },
    syncTimestamp: { type: "number", storageKey: "-ybpxlpWQ7mA" },
    type: { type: "string", storageKey: "Pe3jiWZ9aGZS" },
  },
};
