import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://kaghati-shopify-v4.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Order",
  fields: {
    needsDelayedProcessing: {
      type: "boolean",
      default: false,
      storageKey: "EBj1Ra6mp7KE",
    },
  },
  shopify: {
    fields: [
      "additionalFees",
      "billingAddress",
      "browserIp",
      "buyerAcceptsMarketing",
      "cancelReason",
      "cancellation",
      "cancelledAt",
      "cartToken",
      "checkoutToken",
      "clientDetails",
      "closedAt",
      "currency",
      "currentSubtotalPrice",
      "currentSubtotalPriceSet",
      "currentTotalAdditionalFeesSet",
      "currentTotalDiscounts",
      "currentTotalDiscountsSet",
      "currentTotalDutiesSet",
      "currentTotalPrice",
      "currentTotalPriceSet",
      "currentTotalTax",
      "currentTotalTaxSet",
      "customer",
      "customerLocale",
      "discountApplications",
      "discountCodes",
      "email",
      "estimatedTaxes",
      "financialStatus",
      "fulfillmentEvents",
      "fulfillmentOrders",
      "fulfillmentStatus",
      "fulfillments",
      "fulfillmentsCount",
      "landingSite",
      "lineItems",
      "location",
      "merchantOfRecordAppId",
      "name",
      "note",
      "noteAttributes",
      "number",
      "orderNumber",
      "orderStatusUrl",
      "originalTotalAdditionalFeesSet",
      "originalTotalDutiesSet",
      "paymentGatewayNames",
      "phone",
      "poNumber",
      "presentmentCurrency",
      "processedAt",
      "referringSite",
      "refunds",
      "retailLocation",
      "risk",
      "shippingAddress",
      "shippingLines",
      "shop",
      "shopifyCreatedAt",
      "shopifyProtect",
      "shopifyUpdatedAt",
      "sourceIdentifier",
      "sourceName",
      "sourceUrl",
      "statusPageUrl",
      "subtotalPrice",
      "subtotalPriceSet",
      "tags",
      "taxExempt",
      "taxLines",
      "taxesIncluded",
      "test",
      "token",
      "totalCashRoundingAdjustment",
      "totalDiscounts",
      "totalDiscountsSet",
      "totalLineItemsPrice",
      "totalLineItemsPriceSet",
      "totalOutstanding",
      "totalPrice",
      "totalPriceSet",
      "totalShippingPriceSet",
      "totalTax",
      "totalTaxSet",
      "totalTipReceived",
      "totalWeight",
      "transactions",
      "transactionsCount",
    ],
  },
};
