import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://kaghati-shopify-v4.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    metaFieldId: { type: "number", storageKey: "6S4wD1wYI4yz" },
    onlineInventory: {
      type: "json",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "kaghati",
        key: "inventory",
        metafieldType: "json",
        allowMultipleEntries: false,
      },
      storageKey: "bQsS9ZdxnDVV",
    },
    pinCodeData: {
      type: "json",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "kaghati",
        key: "pinCodeData",
        metafieldType: "json",
        allowMultipleEntries: false,
      },
      storageKey: "vHU9aRwTaBn5",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "articles",
      "assets",
      "blogs",
      "bulkOperations",
      "carrierServices",
      "carts",
      "checkoutApiSupported",
      "city",
      "collections",
      "collects",
      "comments",
      "cookieConsentLevel",
      "countries",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerAddresses",
      "customerEmail",
      "customers",
      "discountCodes",
      "discounts",
      "domain",
      "draftOrderLineItems",
      "draftOrderPlatformDiscount",
      "draftOrderPlatformDiscountAllocation",
      "draftOrders",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "forceSsl",
      "fulfillmentEvents",
      "fulfillmentLineItems",
      "fulfillmentOrderLineItems",
      "fulfillmentOrders",
      "fulfillmentServices",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "inventoryItems",
      "inventoryLevels",
      "latitude",
      "locations",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderLineItems",
      "orderTransactions",
      "orders",
      "pages",
      "passwordEnabled",
      "paymentSchedule",
      "paymentTerms",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "priceRules",
      "primaryLocale",
      "primaryLocation",
      "productImages",
      "productMedia",
      "productOptions",
      "productVariantMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "provinces",
      "redirects",
      "refundLineItems",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "scriptTags",
      "setupRequired",
      "shippingLines",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "themes",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
