import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "khagatiOrder" model, go to https://kaghati-shopify-v4.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "__Ukqgm8scDS",
  fields: {
    additionalFees: { type: "json", storageKey: "jPSbbTMBvLHr" },
    billingAddress: { type: "json", storageKey: "-Lw3Rhiscsjt" },
    browserIp: { type: "string", storageKey: "YSt9vJncJ0rt" },
    buyerAcceptsMarketing: {
      type: "boolean",
      storageKey: "h2CT180fR0ur",
    },
    cancelReason: { type: "string", storageKey: "KO3NXKASdipy" },
    cancellation: { type: "json", storageKey: "LG_RUWADOmsU" },
    cancelledAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "r2giA7hO4YhE",
    },
    cartToken: { type: "string", storageKey: "jBODTswdpz6C" },
    checkoutToken: { type: "string", storageKey: "QnmQlK--QWud" },
    clientDetails: { type: "json", storageKey: "WM-dIbsWKVq3" },
    closedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "YkJQC6FWvVwA",
    },
    currency: { type: "string", storageKey: "RQeSOJzAoc1r" },
    currentSubtotalPrice: {
      type: "string",
      storageKey: "Bnf5prvesiCy",
    },
    currentSubtotalPriceSet: {
      type: "json",
      storageKey: "JFJpC9GrKBgr",
    },
    currentTotalAdditionalFeesSet: {
      type: "json",
      storageKey: "s_-NQ_3iYwRH",
    },
    currentTotalDiscounts: {
      type: "string",
      storageKey: "jRF0Svyk8tmS",
    },
    currentTotalDiscountsSet: {
      type: "json",
      storageKey: "j-KbKMnai4A0",
    },
    currentTotalDutiesSet: {
      type: "json",
      storageKey: "O6xxZoV-N7w4",
    },
    currentTotalPrice: { type: "string", storageKey: "xD8XWVtLNYzT" },
    currentTotalPriceSet: {
      type: "json",
      storageKey: "kd1M0WDXfNCP",
    },
    currentTotalTax: { type: "string", storageKey: "2flL40bgpYh4" },
    currentTotalTaxSet: { type: "json", storageKey: "v-aBbmaLbuf0" },
    customer: { type: "json", storageKey: "VH76-SiOBT-g" },
    customerLocale: { type: "string", storageKey: "qHt6ui45pZUY" },
    discountApplications: {
      type: "json",
      storageKey: "66b5LCDuXj-z",
    },
    discountCodes: { type: "json", storageKey: "T5ywEFqsNe32" },
    email: { type: "string", storageKey: "ORj-I4Ep63sX" },
    estimatedTaxes: { type: "boolean", storageKey: "Dzyc8APYYesB" },
    financialStatus: { type: "string", storageKey: "SBnhdW6QZIiB" },
    fulfillmentEvents: { type: "json", storageKey: "rL19p8BvnuhV" },
    fulfillmentOrders: { type: "json", storageKey: "hgZ7QHIPommd" },
    fulfillmentStatus: { type: "string", storageKey: "rOYsnfUwt5xK" },
    fulfillments: { type: "json", storageKey: "GBsqeQUkLMDW" },
    landingSite: { type: "url", storageKey: "HdzqaWGzIZcp" },
    lineItems: { type: "json", storageKey: "OMxTIZHpfHqd" },
    location: { type: "json", storageKey: "FXPfZnjBtTGv" },
    merchantOfRecordAppId: {
      type: "number",
      storageKey: "42FkC3hztAv3",
    },
    name: { type: "string", storageKey: "eflU6H0qOTLF" },
    note: { type: "string", storageKey: "V-8R1X8-Sxb7" },
    noteAttributes: { type: "json", storageKey: "L06CBlb578oq" },
    number: { type: "number", storageKey: "ZrlsAgbiHg9h" },
    orderId: { type: "string", storageKey: "weElZbF6WNah" },
    orderNumber: { type: "number", storageKey: "_Kew9L-2AX5c" },
    orderStatusUrl: { type: "url", storageKey: "5l-pFtFJOlf7" },
    originalTotalAdditionalFeesSet: {
      type: "json",
      storageKey: "vclA-w-duEkL",
    },
    originalTotalDutiesSet: {
      type: "json",
      storageKey: "VnERcLdSxDQp",
    },
    paymentGatewayNames: { type: "json", storageKey: "CCcfJXgW-nqb" },
    phone: { type: "string", storageKey: "c7uXX4hPdlMz" },
    poNumber: { type: "string", storageKey: "mWDKE5OTu2gN" },
    presentmentCurrency: {
      type: "string",
      storageKey: "mzF6jmv6by3M",
    },
    processedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "uvNQLqjMEuBk",
    },
    referringSite: { type: "string", storageKey: "HolNHm0KJAw5" },
    refunds: { type: "json", storageKey: "gihKh5ii6qHF" },
    shippingAddress: { type: "json", storageKey: "lJgslNh8PPpJ" },
    shippingLines: { type: "json", storageKey: "mWIkIyCacYwt" },
    shop: { type: "json", storageKey: "PkM7BTP8r7x-" },
    shopifyCreatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "WD19mLXRcLvN",
    },
    shopifyProtect: { type: "json", storageKey: "AcbV-IlkmEmb" },
    shopifyUpdatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "pkDBG_2dRyqJ",
    },
    sourceIdentifier: { type: "string", storageKey: "QASksw9oGZIv" },
    sourceName: { type: "string", storageKey: "oCJ3tUxb-5W7" },
    sourceUrl: { type: "url", storageKey: "vzm3D3gKyV82" },
    subtotalPrice: { type: "string", storageKey: "Di_Ys8sWr7bK" },
    subtotalPriceSet: { type: "json", storageKey: "fDNdX5BDyJwp" },
    tags: { type: "json", storageKey: "_TNh0cTUSMlI" },
    taxExempt: { type: "boolean", storageKey: "X6buAGcm1bgB" },
    taxLines: { type: "json", storageKey: "yUO4HqasnbSJ" },
    taxesIncluded: { type: "boolean", storageKey: "7SsBfRy4dQM6" },
    token: { type: "string", storageKey: "nLzD7PVUREtU" },
    totalDiscounts: { type: "string", storageKey: "clF4OTMBRy7E" },
    totalDiscountsSet: { type: "json", storageKey: "6jovxuQgDB68" },
    totalLineItemsPrice: {
      type: "string",
      storageKey: "y1EFvh2Na7sy",
    },
    totalLineItemsPriceSet: {
      type: "json",
      storageKey: "cUuU0AhV6GsA",
    },
    totalOutstanding: { type: "string", storageKey: "QAcAu2CSOPsO" },
    totalPrice: { type: "string", storageKey: "Zxw6KbfoaRbf" },
    totalPriceSet: { type: "json", storageKey: "a4mvrLHOUoam" },
    totalShippingPriceSet: {
      type: "json",
      storageKey: "OXWm7IY5zTh9",
    },
    totalTax: { type: "string", storageKey: "faPiWSdI88J1" },
    totalTaxSet: { type: "json", storageKey: "xyVlMlLwm4Fw" },
    totalTipReceived: { type: "string", storageKey: "KPFdQm9VfYnY" },
    totalWeight: { type: "number", storageKey: "SgrNHOrZfWPy" },
    transactions: { type: "json", storageKey: "itoHrn37NksU" },
  },
};
